/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  javascriptSidebar: [
    {
      type: 'category',
      collapsed: false,
      label: 'JavaScript',
      items: ['javascript/javascript-variable-and-scopes', 'javascript/javascript-data-types', ]
    }
  ],
  dataStructureSidebar: [
    {
      type: 'category',
      collapsed: false,
      label: 'Data Structure',
      items: ['data_structure/data-structure-array']
    }
  ]
};

export default sidebars;
